### ISSUE TITLE
Ensure this package is up-to-date with latest v1 context and includes CBOR-LD codec value

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/age-verification-context#4]
For the CBOR-LD value see: https://github.com/convenience-org/age-verification-context/blob/master/js/constants.js#L6

**Comment by davidlehn** [comment]
I'm assuming the "up-to-date with latest v1" means to match what's in the current convenience-org package?  This is now the case.  And the w3id will be changed to point to this repo's context.  If there's another source of truth, please point at it.

**Comment by davidlehn** [comment]
And to follow up, we also have the context in age-vocab repo (with the same protected boolean issue).  Maybe that is the source of truth.
